name: check-flood

on:
  schedule:
    - cron:  '43 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./.github/check-flood
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
