name: index-version
  
on:
  schedule:
    - cron:  '42 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: clone
      uses: actions/checkout@v1
    - name: check index version
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: cat autossh.service
